api_token = ""
show_freshness = false
dry_run = false

[profiles]
names = ["Main"]

[folders]
"Referral Allow" = "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/controld/referral-allow-folder.json"

[profile_folders]
Main = ["Referral Allow"]
